### ISSUE TITLE
Bash Script prompts for additional password 

### ISSUE THREAD

**Issue by bheemreddy181-zz** [adriens/schemacrawler-deb#65]
Is there a way I can bypass this provide password message ? Is this something related to the permissions alone.

I do see the same error on MacOS as well

**Comment by adriens** [comment]
@bheemreddy181 : this is a schemacrawler core issue. Please fill an issue on https://github.com/schemacrawler/SchemaCrawler

Still, if you provide the password in the command line or in the parameter file (very convenient way to use schemacrawler) you should not be prompted.

Also, be sure to provide the command line you used. You will have to use an issue template so you'll be guided.

I close this issue but please feel free to link this issue to the one you'll create :+1:

**Comment by sualeh** [comment]
@adrien - please explain the core issue, and I will fix it.

**Comment by adriens** [comment]
@bheemreddy181 : did you create the ticket on  [SchemaCrawle](https://github.com/schemacrawler/SchemaCrawler)

Did you give a try to schemacrawler configuration file please ?

**Comment by bheemreddy181-zz** [comment]
@adriens I haven't created an issue for this yet, I myself found a workaround by sending an empty String in the password param from the command line. I don't think this is an issue for now. Thanks for your inputs though :-)

**Comment by adriens** [comment]
:+1:
