### ISSUE TITLE
[Enhancement] : Pass Schemacrawler and SchemaCrawler Additional lints Versions as input params for Maven Build

### ISSUE THREAD

**Issue by bheemreddy181-zz** [adriens/schemacrawler-deb#68]
Does it make sense to pass in Additional-lints and SchemaCrawler Lint version to Maven Build So that each time whenever I want to pull latest versions of those, rather than changing the POM each time? I know that Debian package still need to be updated back in the binaries.

Want to hear from you?

I am also thinking about conditional Params which will automatically copy the Additional Lints to the Lib Folder if the flag is set as true.

**Comment by adriens** [comment]
##  Pass in Additional-lints and SchemaCrawler Lint version to Maven Build

I do maintain the additional lint manually, and take care of compatibility. Si I think it's pretty dangerous to do that.

## Conditional Params for putting additional lints to lib

This could be done by overriding something you mean. By default, it would not be embedded, you should force it, that's the approach you're talking about ?

I should take a closer look to [jdeb](https://github.com/tcurdt/jdeb). It could be done through a property or via a postscript. Did you already have a look ?

**Comment by adriens** [comment]
```
mvn install "-Dmyproperty=my property from command line"
```

**Note also, that if you have both a property in the pom, and on the command-line, the command-line takes precedence.**

**Comment by adriens** [comment]
Will be fixed soon :heavy_check_mark:

**Comment by adriens** [comment]
@bheemreddy181 : you can check the build it's described in the `README`.

but... if you want additional lints directly dropped in the debian installer, just :

Pull from `master` then :

```
mvn clean package -Dadditional-lints.target.dir=lib
```

Can you confirm it matches your expectations ?

**Comment by bheemreddy181-zz** [comment]
@adriens you are crazy, it matches my expectation. As far as it is optional I am ok with this. :-) thanks man
