### ISSUE TITLE
[QUESTION] : Schema Crawler Debain Installation Creates two folder 

### ISSUE THREAD

**Issue by bheemreddy181-zz** [adriens/schemacrawler-deb#69]
Why SchemaCrawler Installation Creates two folders in /opt/ folder? Is this something expected ?

**Steps followed** 

1. export SCHEMACRAWLER_VERSION=15.04.01
2. wget  https://github.com/adriens/schemacrawler- 
    deb/releases/download/${SCHEMACRAWLER_VERSION}/schemacrawler- 
    deb_${SCHEMACRAWLER_VERSION}_all.deb
3.sudo dpkg -i schemacrawler-deb_${SCHEMACRAWLER_VERSION}_all.deb

Both have got the same content though - I know that schemacrawler folder is for command line execution, but not sure why a folder with the version name ?

<img width="974" alt="screen shot 2019-02-24 at 7 36 47 pm" src="https://user-images.githubusercontent.com/3464623/53309128-ae64ab80-386b-11e9-8ffe-a5c0915838f3.png">

**Comment by adriens** [comment]
There onlyis one folder `/opt/schemacrawler` is a symbolic link that targets the real directory (the one with the vesion appended) :

![selection_022](https://user-images.githubusercontent.com/5235127/53309574-b587ca00-38fc-11e9-89d7-9c6fe9ac1fc7.jpg)

**Comment by bheemreddy181-zz** [comment]
Cool thanks :-) I am kind of new to these i was little confused

**Comment by adriens** [comment]
Symbolic links are your friends :rofl:
