### ISSUE TITLE
[QUESTION] : Two debain Packages 

### ISSUE THREAD

**Issue by bheemreddy181-zz** [adriens/schemacrawler-deb#71]
Can we have two Debian Packages One with Additional Lints Copied And One without? I know this is weird

**Comment by adriens** [comment]
Fixed with the additional maven option as detailed in the `README.md`

**Comment by bheemreddy181-zz** [comment]
But my question more like can we have two deb packages available to do wget from any Linux machine . Given a privilege to use either of one ?

**Comment by adriens** [comment]
So you would like me to release both as part of the Gihtub release :question:

**Comment by bheemreddy181-zz** [comment]
Yes if it makes sense ?

**Comment by adriens** [comment]
Yes, it does :+1: 
I'll give a look in the next days. If you're in a hurry, don't wait for it.

**Comment by adriens** [comment]
I have to drop and re-release to test the new code :crossed_fingers:

**Comment by bheemreddy181-zz** [comment]
I am confused what does your comment mean ?

**Comment by adriens** [comment]
@bheemreddy181 : is that what you were dreaming about ? :laughing: :rocket: 

![selection_030](https://user-images.githubusercontent.com/5235127/53466143-db4fd300-3aa4-11e9-9e5f-f11c53a14a92.jpg)

https://github.com/adriens/schemacrawler-deb/releases/tag/15.04.01

**Comment by adriens** [comment]
@mbarre ; you may also like it :smile_cat:

**Comment by bheemreddy181-zz** [comment]
Right as I thought Cool Stuff

**Comment by adriens** [comment]
So i can close the issue ? :pray: :question:

**Comment by adriens** [comment]
:fireworks:
