### ISSUE TITLE
Wget is returining 404

### ISSUE THREAD

**Issue by bheemreddy181-zz** [adriens/schemacrawler-deb#75]
<img width="1677" alt="screen shot 2019-03-05 at 8 58 34 am" src="https://user-images.githubusercontent.com/3464623/53814267-ef705600-3f24-11e9-9343-e9677e930b5a.png">

**Comment by adriens** [comment]
Bad documentation

````
https://github.com/adriens/schemacrawler-deb/releases/download/15.04.01/schemacrawler-deb-15.04.01_all.deb
```

I have to fix the `README`

**Comment by bheemreddy181-zz** [comment]
will create a PR

**Comment by adriens** [comment]
Sorry for anoyance :pray:

**Comment by bheemreddy181-zz** [comment]
Working as expected.
